import systems
# test를 위한 command 모음

def test1():
    sys = systems.system()
    sys.add_node("add node 1,1")
    sys.add_node("add node 1,5")
    sys.add_node("add node 1,10")
    sys.add_node("add node 1,15")
    sys.add_node("add node 1,20")
    sys.add_node("add node 5,1")
    sys.add_node("add node 5,5")
    sys.add_node("add node 5,10")
    sys.add_node("add node 5,15")
    sys.add_node("add node 5,20")
    sys.add_node("add node 10,1")
    sys.add_node("add node 10,5")
    sys.add_node("add node 10,10")
    sys.add_node("add node 10,15")
    sys.add_node("add node 10,20")
    sys.add_node("add node 15,1")
    sys.add_node("add node 15,5")
    sys.add_node("add node 15,10")
    sys.add_node("add node 15,15")
    sys.add_node("add node 15,20")
    sys.add_node("add node 20,1")
    sys.add_node("add node 20,5")
    sys.add_node("add node 20,10")
    sys.add_node("add node 20,15")
    sys.add_node("add node 20,20")
    sys.update()
    sys.set_interfer("set interfer 11 50")
    sys.add_user("add user 1,1")
    sys.simul_start("simul start 20,20")
    return sys.user.whole_error()

def test2():
    sys = systems.system()
    sys.add_random("add random 10")
    sys.update()
    sys.set_interfer("set interfer 11 50")
    sys.add_user("add user 1,1")
    sys.simul_start("simul start 20,20")
    return sys.user.whole_error()

def test3():
    sys = systems.system()
    sys.add_node("add node 1,1")
    sys.add_node("add node 1,5")
    sys.add_node("add node 1,15")
    sys.add_node("add node 1,20")
    sys.add_node("add node 5,1")
    sys.add_node("add node 5,20")
    sys.add_node("add node 8,1")
    sys.add_node("add node 8,20")
    sys.add_node("add node 10,1")
    sys.add_node("add node 10,20")
    sys.add_node("add node 15,1")
    sys.add_node("add node 15,20")
    sys.add_node("add node 20,1")
    sys.add_node("add node 20,5")
    sys.add_node("add node 20,15")
    sys.add_node("add node 20,20")
    sys.update()
    # sys.set_interfer("set interfer 11 50")
    sys.add_user("add user 1,1")
    sys.simul_start("simul start 20,20")
    return sys.user.whole_error()

def test4():
    sys = systems.system()
    sys.add_node("add node 1,1")
    sys.set_channel("set channel 1,1 11")
    sys.add_node("add node 1,5")
    sys.set_channel("set channel 1,1 11")
    sys.add_node("add node 1,15")
    sys.set_channel("set channel 1,15 16")
    sys.add_node("add node 1,20")
    sys.set_channel("set channel 1,20 16")
    sys.add_node("add node 5,1")
    sys.set_channel("set channel 5,1 11")
    sys.add_node("add node 5,20")
    sys.set_channel("set channel 5,20 16")
    sys.add_node("add node 8,1")
    sys.set_channel("set channel 8,1 11")
    sys.add_node("add node 8,20")
    sys.set_channel("set channel 8,20 16")
    sys.add_node("add node 10,1")
    sys.set_channel("set channel 10,1 21")
    sys.add_node("add node 10,20")
    sys.set_channel("set channel 10,20 26")
    sys.add_node("add node 15,1")
    sys.set_channel("set channel 15,1 21")
    sys.add_node("add node 15,20")
    sys.set_channel("set channel 15,20 26")
    sys.add_node("add node 20,1")
    sys.set_channel("set channel 20,1 21")
    sys.add_node("add node 20,5")
    sys.set_channel("set channel 20,5 21")
    sys.add_node("add node 20,15")
    sys.set_channel("set channel 20,15 26")
    sys.add_node("add node 20,20")
    sys.set_channel("set channel 20,20 26")
    sys.update()
    sys.set_interfer("set interfer 11 5")
    #sys.set_interfer("set interfer 16 50")
    #sys.set_interfer("set interfer 21 50")
    #sys.set_interfer("set interfer 26 50")
    sys.add_user("add user 1,1")
    sys.simul_start("simul start 20,20")
    return sys.user.whole_error()

def test5():
    sys = systems.system()
    sys.add_node("add node 1,1")
    sys.set_channel("set channel 1,1 11")
    sys.add_node("add node 1,5")
    sys.set_channel("set channel 1,1 11")
    sys.add_node("add node 1,15")
    sys.set_channel("set channel 1,15 11")
    sys.add_node("add node 1,20")
    sys.set_channel("set channel 1,20 11")
    sys.add_node("add node 5,1")
    sys.set_channel("set channel 5,1 11")
    sys.add_node("add node 5,20")
    sys.set_channel("set channel 5,20 11")
    sys.add_node("add node 8,1")
    sys.set_channel("set channel 8,1 11")
    sys.add_node("add node 8,20")
    sys.set_channel("set channel 8,20 11")
    sys.add_node("add node 10,1")
    sys.set_channel("set channel 10,1 26")
    sys.add_node("add node 10,20")
    sys.set_channel("set channel 10,20 26")
    sys.add_node("add node 15,1")
    sys.set_channel("set channel 15,1 26")
    sys.add_node("add node 15,20")
    sys.set_channel("set channel 15,20 26")
    sys.add_node("add node 20,1")
    sys.set_channel("set channel 20,1 26")
    sys.add_node("add node 20,5")
    sys.set_channel("set channel 20,5 26")
    sys.add_node("add node 20,15")
    sys.set_channel("set channel 20,15 26")
    sys.add_node("add node 20,20")
    sys.set_channel("set channel 20,20 26")
    sys.update()
    sys.set_interfer("set interfer 11 5")
    #sys.set_interfer("set interfer 16 50")
    #sys.set_interfer("set interfer 21 50")
    sys.set_interfer("set interfer 26 10")
    sys.add_user("add user 1,1")
    sys.simul_start("simul start 20,20")
    return sys.user.whole_error()

# 지정한 simulation을 100번씩 반복
def test_log(test_num):
    log = 0
    log_num = 0
    for i in range(5):
        if test_num == 1: log += test1()
        if test_num == 2: log += test2()
        if test_num == 3: log += test3()
        if test_num == 4: log += test4()
        if test_num == 5: log += test5()
        log_num += 1
    print("        Average Error", log / log_num, "meter")
    return log / log_num
